In [25]:
import numpy as np

2. Create a null vector of size 10

In [26]:
v1 = np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a null vector of size 10 but the fifth value which is 1

In [27]:
v2 = v1.copy()
v2[4] = 1
v2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4. Create a vector with values ranging from 10 to 49

In [28]:
v3 = np.arange(10,49)
v3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

5. Reverse a vector (the first element becomes last)

In [29]:
v4 = np.arange(10)
print("vector: ", v4)
print("reverse vector: ", v4[::-1])

# can also use flip method- np.flip(v4)

vector:  [0 1 2 3 4 5 6 7 8 9]
reverse vector:  [9 8 7 6 5 4 3 2 1 0]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
m1 = np.matrix(range(9))
m1.shape = (3,3)
m1

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

7. Find indices of non­zero elements from [1,2,0,0,4,0]

In [31]:
l1 = [1,2,0,0,4,0]

non_zero_indices = [l1.index(i) for i in l1 if i != 0]
non_zero_indicesFind indices of nonzero elements from [1,2,0,0,4,0]

SyntaxError: invalid syntax (<ipython-input-31-050c7bbfb079>, line 4)

8. Create a 3x3x3 array with random values

In [32]:
import random
a = np.random.randint(10, 100, (3,3,3))
a

array([[[20, 85, 46],
        [51, 23, 25],
        [76, 62, 30]],

       [[57, 57, 75],
        [61, 68, 58],
        [76, 85, 40]],

       [[64, 73, 75],
        [96, 14, 93],
        [66, 94, 19]]])

In [33]:
a.shape

(3, 3, 3)

9. Create a random vector of size 30 and find the mean value

In [34]:
b = np.array([random.randint(10,80) for i in range(30)])
print("Random vector of size 30: ", b)
print("Size of this vector: ", b.size)
print("Mean of this vector: ", round(b.mean(), 2))

Random vector of size 30:  [43 19 56 16 65 70 23 65 51 36 76 77 14 35 20 71 52 19 18 11 46 25 42 49
 65 20 48 28 48 38]
Size of this vector:  30
Mean of this vector:  41.53


10. Create a 2d array with 1 on the border and 0 inside

In [35]:
c = np.array([[1,1,1], [1,0,1], [1,1,1]])
print("2D array with 1 on the outside and zero inside \n", c)
print("Dimention of array", c.ndim)

2D array with 1 on the outside and zero inside 
 [[1 1 1]
 [1 0 1]
 [1 1 1]]
Dimention of array 2


11. Create an 8x8 matrix and fill it with a checkerboard pattern

In [36]:
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


12. What is the major difference between sets, lists, tuples, and dictionaries?

 list	                   tuple	                     set	                                     dictionary
-Denoted by[]	          -Denoted by ()	           -Denoted by {}	                             -Denoted by {}
-Ordered data structure	  -Ordered data structure	   -Unordered data structure	                 -Unordered data structure
-Allows all data types 	  -Allows all data types 	   -Allows all data types other than boolean     -Allows all data types 
-Allows duplicates	      -Allows duplicates	       -No duplicates	                             -Overwrites the duplicates
-mutable       	          -immutable	               -Mutable(allow addition and exclusion)        -mutable



13. Print first 10 natural numbers using while loop

In [37]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


14. Print the numbers -10 to -1 using for loop.

In [38]:
for i in range(-10, 0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


15. Print the message “Done” after successful execution of any for loop. 

Modifying the above loop for printing numbers -10 to -1 to print "Done" after the successful completion of the loop.

In [39]:
n = 0
while n != -1:
    for i in range(-10, 0):
        print(i)
        n = i
print("Done")

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
Done


16. Create a random vector of size 10 and sort it

In [40]:
r = np.random.randint(10, 100, (10))
print("Random vector: ", r)
r.sort()
print("Sorted random vector:", r)

Random vector:  [22 27 26 49 67 72 14 61 54 85]
Sorted random vector: [14 22 26 27 49 54 61 67 72 85]


17. Execute any three math functions using numpy.

In [41]:
print("Mean of vector:",r.mean())
print("SD of vector:", r.std())
print("Sum of vector:", r.sum())

Mean of vector: 47.7
SD of vector: 22.95234192843946
Sum of vector: 477
